
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
modbus: !include includes/modbus.yaml

homeassistant:
  customize: !include customize.yaml   # <-- переносим сюда
  packages: !include_dir_merge_named includes/packages


#Telegram
#api_key_bot: "2140345378:AAGNyUXaSRtgiIRU9hQTI-jFTAIt5lzHMaw"
#telegram_id_vital: "374673383"
#telegram_id_oksana: "496868345"

shell_command:
  ha_gitpush: "/bin/bash /config/ha_gitpush.sh"
